import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from "react-router";
import annual from "../../assets/annual.jpg";
export default function Hero() {
    return (_jsx("div", { className: "w-full bg-white flex justify-center overflow-hidden", children: _jsxs("div", { className: "w-full max-w-9xl mx-auto", children: [_jsxs("div", { className: "flex flex-col lg:flex-row items-stretch min-h-[600px]", children: [_jsxs("div", { className: "relative flex-shrink-0 w-full lg:w-[45%] xl:w-[850px]", children: [_jsx("div", { className: "absolute top-0 left-0 right-0", style: { height: 130, background: "var(--button-yellow, #f5a623)" } }), _jsx("div", { className: "relative z-10 px-4 md:px-0 md:pl-[3vw] pt-5 mx-auto", children: _jsx("img", { src: annual, alt: "Annual report cover", className: "\n      w-full \n      max-w-[600px] \n      md:max-w-[700px] \n      lg:max-w-[900px]\n      h-[220px] \n      sm:h-[280px] \n      md:h-[400px] \n      lg:h-[55vh]\n      object-cover \n      object-top \n      rounded-3xl\n    " }) })] }), _jsxs("div", { className: "flex-1 flex flex-col", children: [_jsx("div", { className: "flex items-center justify-center px-4 text-center bg-transparent md:bg-[#f5a623] py-6 sm:py-8 md:py-10", children: _jsx("h1", { className: "text-black font-bold", style: {
                                            fontSize: "clamp(2.5rem, 8vw, 5rem)",
                                            lineHeight: 1
                                        }, children: "Annual Reports" }) }), _jsx("div", { className: "absolute right-0  overflow-hidden w-28 h-30", children: _jsx("img", { src: "https://happybarnutrition.org/wp-content/uploads/2024/05/BOOING-PEEK.gif", alt: "Duck Peek", className: "w-32 h-auto animate-peek" }) }), _jsxs("div", { className: "flex flex-col justify-center items-center text-center py-2 sm:py-10 md:py-12 lg:py-14 px-4 sm:px-6 md:px-8 lg:px-10", style: { flex: 1 }, children: [_jsxs("p", { className: "font-extrabold mb-3 md:mb-8 max-w-2xl leading-tight", style: {
                                                color: "var(--text-purple, #5e2a7c)",
                                                fontSize: "clamp(1.5rem, 5vw, 3.2rem)",
                                                // lineHeight: 1.2
                                            }, children: ["Thank You to Our Donors. ", _jsx("br", {}), "Nothing is possible without YOU!"] }), _jsxs("p", { className: " mb-6 md:mb-8 max-w-3xl  md:font-semibold text-gray-500 leading-relaxed md:leading-tight text-xl", children: ["Our Annual Reports are published with an intent to update our donors, partners, volunteers and the general public on our activities, progress and goals.", _jsx("br", {}), _jsx("br", {}), "They also contain metrics on the number of children/elders supported, the number of locations/campaigns supported, etc.", _jsx("br", {}), _jsx("br", {}), "The Annual Report is typically released in February of the following year."] }), _jsxs("p", { className: "font-bold max-w-2xl", style: {
                                                color: "var(--link-blue, #2c6e9e)",
                                                fontSize: "clamp(0.75rem, 2.5vw, 1rem)",
                                                lineHeight: 1.5
                                            }, children: [_jsx(Link, { to: "/", className: "hover:underline", children: "Happy Bar Nutrition" }), " ", _jsx("span", { style: { color: "var(--text-purple, #5e2a7c)" }, children: "Inc. (est. 2016) is a US 501(c)(3) non-profit organisation" })] })] })] })] }), _jsx("div", { className: "relative -mt-1 overflow-hidden", children: _jsxs("svg", { viewBox: "0 0 1440 120", xmlns: "http://www.w3.org/2000/svg", preserveAspectRatio: "none", className: "block w-full", style: { height: "clamp(60px, 8vw, 120px)" }, children: [_jsx("rect", { width: "1440", height: "120", fill: "#ffffff" }), _jsx("path", { d: "M0,20 C300,80 700,0 1000,50 C1200,80 1350,20 1440,40 L1440,120 L0,120 Z", fill: "var(--light-blue, #7bc5d9)", opacity: "0.5" }), _jsx("path", { d: "M0,45 C200,10 500,75 800,35 C1050,5 1280,65 1440,30 L1440,120 L0,120 Z", fill: "var(--mid-blue, #4ba0b8)", opacity: "0.7" }), _jsx("path", { d: "M0,65 C250,30 600,90 900,55 C1100,30 1300,75 1440,55 L1440,120 L0,120 Z", fill: "var(--dark-blue, #1f6d84)" })] }) })] }) }));
}
