// Sample image URLs - replace with your actual image URLs
const IMAGE_URLS = {
    child1: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&h=600&fit=crop",
    children2: "https://images.unsplash.com/photo-1509062522246-3755977927d7?w=800&h=600&fit=crop",
    girl: "https://images.unsplash.com/photo-1516627145497-ae6968895b74?w=800&h=600&fit=crop",
    leprosyMap: "https://happybarnutrition.org/wp-content/uploads/2024/05/image.png",
    support: "https://static.wixstatic.com/media/42a459_90b63fa5f9ca4aca9c106c3e5b7473dd~mv2.jpg/v1/fill/w_350,h_359,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/42a459_90b63fa5f9ca4aca9c106c3e5b7473dd~mv2.jpg"
};
export const blogPosts = [
    {
        slug: "empathy-in-classroom",
        title: "When I think about Empathy…….",
        date: "May 18, 2024",
        category: "General | Kids | Schools",
        excerpt: "In a remote village far from the city, the school bell rings, children walk into their classrooms, few dragging their feet, some with big smiles, some with tired eyes. Miss Mary walks in and starts...",
        image: "https://happybarnutrition.org/wp-content/uploads/2024/06/kids-in-front-of-run-down-school.webp",
        blocks: [
            { type: "text", content: "In a remote village far from the city, the school bell rings, children walk into their classrooms, few dragging their feet, some with big smiles, some with tired eyes." },
            { type: "text", content: "Miss Mary walks in and starts teaching. She tries engaging the children by asking questions." },
            { type: "text", content: "*No hands up.*" },
            { type: "text", content: "She wants to shake them up, to get them going. She asks them to stand up and look to the right, look to the left, and greet the person next to them. Children stand up reluctantly and their silent sighs fills the classroom." },
            { type: "text", content: "The teacher knows what the problem is." },
            { type: "text", content: "She asks everyone to sit back down. They cannot focus on what she is saying as they are hungry. They have not had anything to eat. The last they have eaten was the previous day at lunch time. Despite this, they have walked miles to get to school barefoot or with tattered footwear." },
            { type: "image", src: "https://happybarnutrition.org/wp-content/uploads/2024/06/image-e1715999318759.webp", alt: "Children in classroom" },
            { type: "text", content: "Its heart wrenching for Miss Mary although it is a small burden to bear, compared to what the children are going through. Miss Mary continues, doing her best. Every so often, the children's eyes keep looking at the door. The tired eyes, looking longingly for something to arrive." },
            { type: "text", content: "Miss Mary is disturbed by the rustling and the whispers behind her and turns around to face the children. She faces a joyous sight; all children their eyes lit up like a beautiful Christmas tree, stare back at her." },
            { type: "text", content: "Miss Mary meets the Happy Bar Delivery Man at the door picks up a box of bars that have come all the way from a far-off city to their very remote village and school. Miss Mary knows the children cannot wait any longer and rushes to give them the one bar that they have waited 20 hours for." },
            { type: "text", content: "She watches while the children quickly unwrap the bars and gobble it down with gladness." },
            { type: "text", content: "Few of them stop to look up and smile, some start chatting with their friends, there is an occasional chuckle and giggle, sounds that seem to come from their inner being. There is chatter, playful banter and so much energy in the cramped classroom its infectious and Miss Mary now begins class in real earnest knowing that the children are now ready to listen, their little bodies relishing the sweet delight of the Happy Bar." },
            { type: "image", src: "https://happybarnutrition.org/wp-content/uploads/2024/06/image-1-e1715999344175.webp", alt: "Girl smiling" },
            { type: "text", content: "The Happy Bar team and all its champions strive to get that one bar to every child who has walked many miles in tattered shoes to get to school." },
            { type: "text", content: "Thank you Happy Bar champion donors, you have put yourself in their shoes." },
            { type: "bold", content: "Boing – the Happy Bar mascot says," },
            { type: "bold", content: "Walk in my shoes," },
            { type: "bold", content: "come chase away the blues." },
            { type: "bold", content: "Peek into my classroom" },
            { type: "bold", content: "come shoo away the gloom." },
            { type: "bold", content: "Bring us a happy bar." },
            { type: "bold", content: "and you be the Star." },
        ],
    },
    {
        slug: "tree-line-journey",
        title: "What Lies Beyond the Tree Line?",
        date: "May 16, 2024",
        category: "Leprosy",
        excerpt: "In February of 2014, accompanied by some like-minded friends, I visited several ostracized, leprosy-ridden villages in the south of India, with the aim of improving the nutritional status of children in these villages...",
        image: "https://happybarnutrition.org/wp-content/uploads/2024/05/kid-sitting-on-bench.jpg",
        blocks: [
            { type: "text", content: "In February of 2014, accompanied by some like-minded friends, I visited several ostracized, leprosy-ridden villages in the south of India, with the aim of improving the nutritional status of children in these villages, by providing a high protein energy bar. It was then that I first came to know that there existed a \"World without Physical Pain\". It was also the first time, I understood what a blessing it is that these leprosy patients that suffer so much ghastly disfigurement literally do not feel physical pain." },
            { type: "text", content: "Quite in contrast, our children with leprosy endure, day in and day out a different kind of pain – pain of separation, the pain of not looking beautiful, the pain of being kept out of schools and colleges, the pain of being cut-off from the society and the pain of losing out on news, food rations, medicines, healthcare etc." },
            { type: "text", content: "The Happy Bar and the Happy Bar team were created to help bring nutrition and good health to them in their villages, so that their health would improve, and they would be less prone to catch the disease. Our hope is that over time, some will be healthy enough to leave the village and become part of the society that they are kept out of." },
            { type: "text", content: "The Happy Bar team and all its champions strive to get Happy Bars to the children and adults of the villages so that they can grow to step into a world outside theirs." },
            { type: "text", content: "I cannot imagine how one of our children might be feeling but I thought I'd jot down a few lines that express what the children or their parents have told me over time about their hopes and aspirations, that they would like told." },
            { type: "bold", content: "Thoughts of a child:" },
            { type: "bold", content: "I look yonder beyond the tree line." },
            { type: "bold", content: "Wondering how good it would be." },
            { type: "bold", content: "To step into the new world" },
            { type: "bold", content: "The world beyond me" },
            { type: "text", content: "" },
            { type: "bold", content: "Lend me a hand dear stranger." },
            { type: "bold", content: "Let me peek at the wonder." },
            { type: "bold", content: "A wonder lies beyond the trees." },
            { type: "bold", content: "The dreams beyond my means." },
            { type: "text", content: "" },
            { type: "bold", content: "Look at me dear brother." },
            { type: "bold", content: "See me, beyond my skin." },
            { type: "bold", content: "We both are hurting." },
            { type: "bold", content: "From outside and within." },
            { type: "text", content: "" },
            { type: "bold", content: "Lend me your hand dear friend." },
            { type: "bold", content: "And help me cross the threshold." },
            { type: "bold", content: "I know I can make it." },
            { type: "bold", content: "If you meet me there." },
        ],
    },
    {
        slug: "leprosy-international-impact",
        title: "Leprosy's International Impact.",
        date: "May 16, 2024",
        category: "Leprosy",
        excerpt: "A quick google search will show - leprosy isn't a part of the past. 150 years since it's discovery and this biblical disease still causes problems and a severely separating social stigma!",
        image: "https://happybarnutrition.org/wp-content/uploads/2024/06/leprosy-feet.webp",
        blocks: [
            { type: "text", content: "A quick google search will show – leprosy isn't a part of the past." },
            { type: "text", content: "150 years since it's discovery and this biblical disease still causes problems and a severely separating social stigma!" },
            { type: "text", content: "Leprosy, also known as Hansen's disease, is a chronic infectious disease that affects the skin, nerves, and mucous membranes. Despite being curable and preventable, it continues to be a public health concern in many parts of the world, particularly in developing countries." },
            { type: "text", content: "In recent news, there have been several stories highlighting the ongoing challenges of leprosy in different parts of the world." },
            { type: "text", content: "We will briefly explore some of those stories below…" },
            { type: "text", content: "[As per the World Health Organization, below is a map of the annual new cases of leprosy around the world.]" },
            { type: "image", src: IMAGE_URLS.leprosyMap, alt: "World map of leprosy cases" },
            { type: "bold", content: "\"Two Cases in Portugal, Imported from Brazil\"" },
            { type: "text", content: "In February 2023, Portuguese health authorities confirmed two cases of leprosy in Lisbon, both of which were imported from Brazil. According to the officials, the patients had traveled to Brazil and had probably contracted the disease there." },
            { type: "text", content: "This incident highlights the importance of early diagnosis and treatment, as well as the need for international cooperation in controlling the spread of leprosy." },
            { type: "bold", content: "\"Brazil States 17,000 Leprosy Cases in 2022\"" },
            { type: "text", content: "Brazil has one of the highest burdens of leprosy in the world, with an estimated 17,000 new cases reported in 2022. This figure represents a slight decrease from the previous year, but it is still a cause for concern." },
            { type: "text", content: "The Brazilian government has implemented several initiatives to improve leprosy control, including increasing access to diagnosis and treatment, providing support to patients and their families, and conducting educational campaigns to raise awareness about the disease." },
            { type: "bold", content: "\"Leprosy is Spreading Faster than Ever Amongst Indian Tea Pickers\"" },
            { type: "text", content: "In India, leprosy continues to be a significant health problem, particularly amongst marginalized communities such as tea pickers. A recent study found that the incidence of leprosy among tea pickers was increasing at an alarming rate, with many cases going undiagnosed and untreated. According to the Leprosy Mission, tea plantations in Sylhet employ about 600,000 workers – mostly women from minority groups – have the highest rate of leprosy in the world!!" },
            { type: "text", content: "This highlights the need for targeted interventions that take into account the specific challenges faced by vulnerable groups such as tea pickers, as well as the importance of early detection and treatment." },
            { type: "bold", content: "\"Sri Lanka had Leprosy under Control Until Covid-19\"" },
            { type: "text", content: "Sri Lanka has been praised for its successful efforts in controlling leprosy in recent years, with the country achieving the World Health Organization's (WHO) target of reducing leprosy prevalence to less than one case per 10,000 population in 2016." },
            { type: "text", content: "However, the COVID-19 pandemic has had a significant impact on leprosy control efforts, with many health resources diverted to pandemic response activities. This has led to delays in diagnosis and treatment, as well as disruptions to surveillance and monitoring activities." },
            { type: "text", content: "According to statistics by the Anti-Leprosy Campaign under the country's Ministry of Health (MOH), more than 1,300 new cases were reported in 2022, with 10.6% of the patients being children. The number of cases for the year 2021 was 1,026 and in 2020, 1,213. The number of cases in 2015 was nearly 2,000." },
            { type: "bold", content: "\"150 Years since Leprosy was Discovered\"" },
            { type: "text", content: "2023 marks the 150th anniversary of the discovery of the causative agent of leprosy, Mycobacterium leprae. Since then, significant progress has been made in understanding the biology of the disease and developing effective treatments. However, much remains to be done in terms of reducing the burden of leprosy, particularly in the poorest and most marginalized communities. This includes ensuring access to early diagnosis and treatment, providing social and economic support to patients and their families, and addressing the stigma and discrimination that often accompanies the disease." },
            { type: "text", content: "In conclusion, these recent news stories underscore the ongoing challenges of leprosy control and the need for sustained efforts to achieve the goal of eliminating leprosy as a public health problem. Happy Bar Nutrition is proud to be able to provide bars to provide strength for those fighting this awful disease, however we feel more needs to be done in raising awareness and erasing the stigma. If anything, Happy Bar Nutrition Inc wants you to know that Leprosy is not an American, Indian, Brazilian, or Sri Lankan problem…it is an 'US' problem, and together we can address the social stigma which has been attached to this sickness for so long." },
            { type: "text", content: "Regards," },
            { type: "text", content: "The Happy Bar Nutrition Family" },
        ],
    },
    {
        slug: "annual-report-2023",
        title: "Happy Bar Nutrition, Inc. Annual Report 2023",
        date: "May 16, 2024",
        category: "General",
        excerpt: "We extend our heartfelt gratitude to you for your unwavering support, whether as a donor, a well-wisher, or a dedicated volunteer. Your generosity has significantly impacted the lives of countless children and elders...",
        image: "https://happybarnutrition.org/wp-content/uploads/2024/06/blog-for-annual-2023-hb-photo-1280x960.webp",
        blocks: [
            { type: "text", content: "We extend our heartfelt gratitude to you for your unwavering support, whether as a donor, a well-wisher, or a dedicated volunteer. Your generosity, in various forms, has significantly impacted the lives of countless children and elders, bringing hope and sustenance to those in need." },
            { type: "text", content: "As we reflect on the past year, we invite you to delve into the pages of the Happy Bar Nutrition Annual Report for 2023. Within its contents, you'll discover the breadth of our endeavors, our ambitious goals, and the remarkable progress we've made in fulfilling our mission." },
            { type: "text", content: "Should you have any queries or insights to share, we encourage you to reach out to Dr. Jack Kennedy (jack.kennedy@happybarnutrition.org) or Dr. Alice Augustine (alice.augustine@happybarnutrition.org). Your input is invaluable as we strive to continually improve and expand our efforts." },
            { type: "text", content: "In these challenging times, the plight of malnourished children and elders is compounded by the burdens of stress and illness. They are deserving of a brighter future—a reality we can collectively create." },
            { type: "text", content: "We humbly request your continued support in any of the following ways:" },
            { type: "text", content: "Contribute directly to Happy Bar Nutrition Inc through our website, https://www.happybarnutrition.org" },
            { type: "text", content: "Advocate for our cause by spreading awareness and encouraging potential donors to join our mission." },
            { type: "text", content: "Here's to a lifetime of health and happiness for you and your family!" },
            { type: "text", content: "Reach out at:" },
            { type: "text", content: "https://www.instagram.com/happybarnutrition" },
            { type: "text", content: "https://www.facebook.com/happybarnutrition" },
        ],
    },
    {
        slug: "81000-bars-support",
        title: "81,000 bars to 23 different groups – all due to YOUR support!!!",
        date: "May 16, 2023",
        category: "General",
        excerpt: "We want to express your deepest appreciation for your unwavering support of Happy Bar Nutrition. Thanks to your generous contributions, this year, we have been able to provide over 80,000 bars...",
        image: "https://happybarnutrition.org/wp-content/uploads/2024/05/My-granparents-have-leprosy.-I-have-to-live-with-them.-We-are-very-poor-scaled.jpg",
        blocks: [
            { type: "text", content: "We want to express our deepest appreciation for your unwavering support of Happy Bar Nutrition." },
            { type: "text", content: "Thanks to your generous contributions, this year, we have been able to provide over 80,000 bars to children who are most in need." },
            { type: "text", content: "Since the beginning of this year, we have distributed these bars to 23 different organizations that focus on various aspects of child care, including schooling, cancer and special needs care, HIV care, and a church-based Leprosy Rehabilitation Center." },
            { type: "text", content: "One of these centers is the Sumanahalli Society, which was established by the Bangalore Archdiocese over 45 years ago to treat and rehabilitate patients with leprosy." },
            { type: "text", content: "To empower the cured individuals to reintegrate into mainstream society, Sumanahalli started a school in 2004 that has already educated more than 13,000 children. They have also successfully placed over 500 cured individuals in government jobs with some earning up to 80,000 rupees a month. Additionally, Sumanahalli has constructed over 300 houses for recovered patients in Bengaluru, settled 169 cured patients in marriages, and expanded its programs to support the disabled by establishing a home for HIV/AIDS patients called \"Support\" and a vocational training institute." },
            { type: "image", src: IMAGE_URLS.support, alt: "81000-bars-support" },
            { type: "text", content: "Your contributions are essential…" },
            { type: "text", content: "Your contributions have been essential in enabling us to distribute over 80,000 bars in the first few months of 2023, and we could not have achieved this without your support. We are deeply grateful for your continued partnership in our mission to provide nutritious and affordable snacks to those who need it most." },
            { type: "text", content: "We are heartened by the generosity of our community and its support for our efforts." },
            { type: "text", content: "Your support has made a significant impact on the lives of those we serve, and we are committed to working hard to ensure that we can reach as many individuals as possible and help them achieve optimal health and wellbeing." },
            { type: "text", content: "Once again, thank you for being an integral part of the Happy Bar Nutrition family." },
            { type: "text", content: "Together, we can make a positive difference in the world." },
        ],
    },
];
