import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { ChevronRight } from "lucide-react";
import girl6 from "../../assets/girl6.jpg";
const heroImage = girl6;
export default function DonationBanner() {
    return (_jsx("div", { className: "w-full overflow-hidden flex justify-center", style: { background: "var(--dark-orange)" }, children: _jsx("div", { className: "w-full max-w-9xl mx-auto", children: _jsx("div", { className: "w-full py-6 sm:py-8 md:py-10 px-4 sm:px-6 md:px-8", children: _jsxs("div", { className: "w-full max-w-6xl mx-auto rounded-2xl px-6 sm:px-8 md:px-10 lg:px-12 py-8 sm:py-10 md:py-12 flex flex-col md:flex-row items-center gap-8 md:gap-10 lg:gap-12", style: { background: "var(--bg-orange)" }, children: [_jsxs("div", { className: "flex-1 text-center", children: [_jsxs("h2", { className: "text-white font-bold leading-tight mb-4 sm:mb-5 md:mb-6", style: { fontSize: "clamp(1.8rem, 5vw, 2.6rem)" }, children: ["Your small change,", _jsx("br", {}), " their big chance!"] }), _jsxs("p", { className: "text-white font-semibold mb-6 sm:mb-7 md:mb-8 leading-snug", style: { fontSize: "clamp(1.8rem, 4vw, 1.35rem)" }, children: [_jsx("span", { style: { color: "#F5C518" }, children: "Just US$ 500 " }), " to start ", _jsx("br", {}), "making a difference"] }), _jsxs("div", { className: "flex flex-col items-center gap-4", children: [_jsxs("button", { className: "group w-full max-w-[260px] font-bold rounded-full cursor-pointer transition-all duration-300 ease-in-out bg-[var(--button-yellow)] hover:bg-[var(--dark-p2)] hover:text-white flex items-center justify-center gap-2 px-5 py-2.5", style: {
                                                //background: "var(--button-yellow)",
                                                color: "#000000",
                                                fontSize: "clamp(0.875rem, 3vw, 1rem)",
                                                border: "none",
                                            }, children: [_jsx("span", { children: "Donate With PayPal" }), _jsx(ChevronRight, { className: "w-4 h-4 opacity-0 -translate-x-2 transition-all duration-300 ease-in-out group-hover:opacity-100 group-hover:translate-x-0", strokeWidth: 2.5 })] }), _jsxs("button", { className: "group w-full max-w-[260px] font-bold rounded-full cursor-pointer transition-all duration-300 ease-in-out bg-[var(--button-blue)] hover:bg-[var(--dark-p2)] flex items-center justify-center gap-2 px-5 py-2.5", style: {
                                                // background: "var(--button-blue)",
                                                color: "#ffffff",
                                                fontSize: "clamp(0.875rem, 3vw, 1rem)",
                                                border: "none",
                                            }, children: [_jsx("span", { children: "Donate With Stripe" }), _jsx(ChevronRight, { className: "w-4 h-4 opacity-0 -translate-x-2 transition-all duration-300 ease-in-out group-hover:opacity-100 group-hover:translate-x-0", strokeWidth: 2.5 })] })] })] }), _jsx("div", { className: "flex-shrink-0 w-full md:w-auto flex justify-center", children: _jsx("img", { src: heroImage, alt: "Child in need", className: "w-full max-w-[280px] sm:max-w-[320px] md:max-w-[380px] lg:max-w-[420px] object-cover", style: { borderRadius: "1rem", height: "auto", maxHeight: "380px" } }) })] }) }) }) }));
}
