import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import child1 from "../../assets/child1.1.jpg";
import child2 from "../../assets/child1.2.jpg";
export default function Year2024() {
    return (_jsx("div", { className: "w-full bg-white py-16 px-6 md:px-12", children: _jsxs("div", { className: " mx-auto", children: [_jsx("div", { className: "flex justify-center mb-16", children: _jsxs("div", { style: { width: "fit-content", textAlign: "center" }, children: [_jsxs("h2", { className: "font-black leading-tight", style: { fontSize: "clamp(2.8rem, 6vw, 4.2rem)" }, children: [_jsx("span", { style: { color: "var(--text-purple-dark)" }, children: "Year " }), _jsx("span", { style: { color: "var(--text-yellow)" }, children: "2024" })] }), _jsx("div", { className: "-mt-2 flex", style: { width: "100%" }, children: _jsx("div", { style: {
                                        flex: 1,
                                        height: "6px",
                                        backgroundImage: "radial-gradient(circle, var(--text-yellow) 3px, transparent 1.5px)",
                                        backgroundSize: "10px 6px",
                                    } }) })] }) }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-3 gap-10 items-center", children: [_jsx("div", { className: "flex justify-center md:justify-start items-start mx-10", children: _jsx("img", { src: child1, alt: "Child in poverty", className: "w-full max-w-md object-cover h-120", style: { borderRadius: "18px", aspectRatio: "3/4" } }) }), _jsxs("div", { className: "text-gray-800 text-lg leading-relaxed", style: { lineHeight: 1.85 }, children: [_jsxs("p", { className: "mb-6", children: [_jsx("span", { style: { color: "#5bb8d4", fontWeight: 700 }, children: "Happy Bar Nutrition" }), " ", "Inc has donated over", " ", _jsx("strong", { children: "2.1 million" }), " Happy Bars to undernourished children and elderly in poverty since 2014."] }), _jsxs("p", { className: "mb-6", children: ["In 2024, we supported ~", _jsx("strong", { children: "3,000 children & 100 adults in 14 locations/campaigns" }), " ", "covering children in 1 leprosy program, 4 HIV/AIDS orphanages, 10 schools for the disadvantaged, 11 cancer and special needs wards for children, and several pre-school & kindergarten child care programs for the underprivileged."] }), _jsx("p", { className: "font-bold", children: "Our goal for 2025 is to donate 500,000 bars." })] }), _jsx("div", { className: "flex justify-center md:justify-start md:pt-16 mx-10", children: _jsx("img", { src: child2, alt: "Smiling child", className: "w-full max-w-md object-cover", style: { borderRadius: "18px", aspectRatio: "3/4" } }) })] })] }) }));
}
